server:
  port: 80
spring:
  application:
    name: cloud-hystrix-feign-order
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #必须是这个名字  server后面必须要加/Eureka
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: hystrix-feign-Order80
    prefer-ip-address: true
ribbon:
  # 建立连接所用的时间,适用于网络状况正常的情况下,两端连接所用的时间
  # 默认等待1秒钟
  ReadTimeout: 3000
  #指的是建立连接后从服务器读取到可用资源所需要的时间
  ConnectTimeout: 1000
  level:
    #feign日志监控的接口 和级别
    com.phoenixhell.springcloud.service.PaymentFeignService: debug
feign:
  hystrix:
    #如果处理自身的容错就开启。开启方式与生产端不一样。
    enabled: true  #开启全局降级fallback 断路器 circuit breaker
