server:
  port: 80
spring:
  application:
    name: cloud-order-server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #必须是这个名字  server后面必须要加/Eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: order80
    prefer-ip-address: true