server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/phoenixrever/spring-cloud.git
          search-paths:
            - springcloud-config
      label: master
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #必须是这个名字  server后面必须要加/Eureka
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: clound-config-server3344
    prefer-ip-address: true