server:
  port: 8004
spring:
  application:
    name: cloud-zookeeper-payment

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: '159629zxc'
  profiles:
    active: home
  cloud:
    zookeeper:
      connect-string: localhost:2181
mybatis:
  type-aliases-package: com.phoenixhell.springcloud.entities
  mapper-locations:  classpath:mapper/*.xml