server:
  port: 80
spring:
  application:
    name: cloud-feign-order
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #必须是这个名字  server后面必须要加/Eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: feignOrder80
    prefer-ip-address: true
ribbon:
  # 建立连接所用的时间,适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所需要的时间
  ConnectTimeout: 5000
logging:
  level:
    #feign日志监控的接口 和级别
   com.phoenixhell.springcloud.service.PaymentFeignService: debug