server:
  port: 80
spring:
  application:
    name: cloud-consul-order
  cloud:
    consul:
      host: 192.168.1.100
      port: 8500
      discovery:
        hostname: localhost
        prefer-ip-address: true
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
